class StringBlit:
    def __init__(self, pattern, reverse=False, rotate=None):
        self.pattern = pattern
        self.reverse = reverse
        self.rotate = rotate
        self.data, self.width = self._compile()

    def _compile(self):
        lines = [l.strip() for l in self.pattern.split('\n') if l.strip()]

        conv = {
            '.': 1 if self.reverse else 0,
            'O': 0 if self.reverse else 1,
        }

        rows = list(map(lambda l: [conv.get(c, -1) for c in l], lines))

        if self.rotate == 'left':
            rows = list(reversed(list(zip(*rows))))
        elif self.rotate == 'right':
            rows = list(zip(*rows[::-1]))

        return [p for row in rows for p in row], len(rows[0])


LABEL_MELODY = StringBlit(
    '''
    ................................
    ................................
    .O...O......OO..........O.......
    .O...O.......O..........O.......
    .OO.OO..OOO..O..OO...OO.O.O...O.
    .O.O.O.O...O.O.O..O.O..OO.O...O.
    .O...O.OOOOO.O.O..O.O...O.O..OO.
    .O...O.O.....O.O..O.O..OO..OO.O.
    .O...O..OOO.OOO.OO...OO.O.....O.
    ..........................O...O.
    ...........................OOO..
    ................................
    ''',
    #        |         |         | #
    reverse=True, rotate='right')


LABEL_DRONE = StringBlit(
    #        |         |         | #
    '''
    ................................
    ................................
    ..OOOO..........................
    ...O..O.........................
    ...O..O.O.OO..OOO..O.OO...OOO...
    ...O..O.OO...O...O.OO..O.O...O..
    ...O..O.O....O...O.O...O.OOOOO..
    ...O..O.O....O...O.O...O.O......
    ..OOOO..O.....OOO..O...O..OOO...
    ................................
    ................................
    ................................
    ''', reverse=True, rotate='right')


LABEL_TROMPETTE = StringBlit(
    #        |         |         | #
    '''
    ................................
    ................................
    ..OOOOO.........................
    ....O...........................
    ....O...O.OO..OOO..OO.O..O.OO...
    ....O...OO...O...O.O.O.O.OO..O..
    ....O...O....O...O.O.O.O.O...O..
    ....O...O....O...O.O.O.O.OO..O..
    ....O...O.....OOO..O...O.O.OO...
    .........................O......
    .........................O......
    ................................
    ''', reverse=True, rotate='right')
